Fix compilation error because of undefined reference (#818)
Fix compilation error introduced in 6a13e275:
undefined reference to `ccl::group_split_type
ccl::v1::comm_split_attr::set<(ccl::v1::comm_split_attr_id)2,
ccl::group_split_type>(ccl::group_split_type const&)'